// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzxopratstazmnfhyjnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56eG9wcmF0c3Rhem1uZmh5am54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzE4NjUsImV4cCI6MjA2NTkwNzg2NX0.IgZzch1K61aq53DH2OPeaZx_vdxVOPX1l9BVcMj4Z60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);